Fix IEEE download

diff --git a/.github/workflows/update-weekly.yml b/.github/workflows/update-weekly.yml
--- a/.github/workflows/update-weekly.yml
+++ b/.github/workflows/update-weekly.yml
@@ -148,31 +148,31 @@ jobs:
 
         # IEEE - IAB
       - name: Download https://standards-oui.ieee.org/iab/iab.csv
-        run:  curl -L -o output/standards_oui_ieee_iab.csv "https://standards-oui.ieee.org/iab/iab.csv"
+        run:  curl -L -o output/standards_oui_ieee_iab.csv "https://standards-oui.ieee.org/iab/iab.csv" || echo "⚠️ Download failed"
 
         # IEEE - MANID
       - name: Download https://standards-oui.ieee.org/manid/manid.csv
-        run:  curl -L -o output/standards_oui_ieee_manid.csv "https://standards-oui.ieee.org/manid/manid.csv"
+        run:  curl -L -o output/standards_oui_ieee_manid.csv "https://standards-oui.ieee.org/manid/manid.csv" || echo "⚠️ Download failed"
 
         # IEEE - IAB
       - name: Download https://standards-oui.ieee.org/iab/iab.csv
-        run:  curl -L -o output/standards_oui_ieee_iab.csv "https://standards-oui.ieee.org/iab/iab.csv"
+        run:  curl -L -o output/standards_oui_ieee_iab.csv "https://standards-oui.ieee.org/iab/iab.csv" || echo "⚠️ Download failed"
 
         # IEEE - OUI36
       - name: Download https://standards-oui.ieee.org/oui36/oui36.csv
-        run:  curl -L -o output/standards_oui_ieee_oui36.csv "https://standards-oui.ieee.org/oui36/oui36.csv"        
+        run:  curl -L -o output/standards_oui_ieee_oui36.csv "https://standards-oui.ieee.org/oui36/oui36.csv" || echo "⚠️ Download failed"      
 
         # IEEE - OUI
       - name: Download https://standards-oui.ieee.org/oui/oui.csv
-        run:  curl -L -o output/standards_oui_ieee_oui.csv "https://standards-oui.ieee.org/oui/oui.csv"        
+        run:  curl -L -o output/standards_oui_ieee_oui.csv "https://standards-oui.ieee.org/oui/oui.csv" || echo "⚠️ Download failed"       
 
         # IEEE - CID
       - name: Download https://standards-oui.ieee.org/cid/cid.csv
-        run:  curl -L -o output/standards_oui_ieee_cid.csv "https://standards-oui.ieee.org/cid/cid.csv"          
+        run:  curl -L -o output/standards_oui_ieee_cid.csv "https://standards-oui.ieee.org/cid/cid.csv" || echo "⚠️ Download failed"         
    
         # IEEE - OPID
       - name: Download https://standards-oui.ieee.org/opid/opid.csv
-        run:  curl -L -o output/standards_oui_ieee_opid.csv "https://standards-oui.ieee.org/opid/opid.csv"      
+        run:  curl -L -o output/standards_oui_ieee_opid.csv "https://standards-oui.ieee.org/opid/opid.csv" || echo "⚠️ Download failed"    
 
         # LOTTUnnels - Domain list
       - name: Download https://raw.githubusercontent.com/LOTTunnels/LOTTunnels.github.io/refs/heads/main/_lottunnels/CSVs/domains.csv
